#!/bin/sh


UNIT="pkg-TorrServer-restart.service"

if [ -x /usr/bin/systemctl ] && /usr/bin/systemctl start "${UNIT}" >/dev/null 2>&1; then
    exit 0
fi

exec /usr/syno/bin/synopkg restart TorrServer
